add possibility to use path stack directories as smarty template
MurgaNikolay/SmartyModule pull request #17
Opened 2015-04-29 11:41 UTC by maglnet

here is a pull request for #16

2016-10-03 20:36 UTC, divix1988 requested changes

2016-10-03 20:36 UTC, divix1988 commented on src/SmartyModule/Service/SmartyRendererFactory.php
> +            && $config['view_manager']['smarty_set_path_stack_dirs']
These two checks with isset($var) && $var doesn't make any sense, change it to 1 check !empty($var) instead.

2016-10-04 08:12 UTC, maglnet commented on src/SmartyModule/Service/SmartyRendererFactory.php
> +            && $config['view_manager']['smarty_set_path_stack_dirs']
Thanks for the hint, done.

2016-10-04 13:52 UTC, divix1988 approved these changes

2021-06-17 19:48 UTC, closed without merging